# version: "3.8" the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

services:
  mongo_db:
    container_name: online-catering-reservation-system-db
    image: mongo:6.0 # Changed from mongo:latest to mongo:6.0 ga error sakong end if mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  catering_api:
    container_name: online-catering-reservation-system-api
    image: drey34/catering:1.0
    build:
      context: ./expressjs-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      - mongo_db
    command: npm run dev # Ensure your dev script is set up to watch changes
    env_file:
      - ./expressjs-backend/.env.development.local # Load environment variables from this file
    develop:
      watch:
        - path: ./expressjs-backend/package-lock.json
          action: rebuild
        - path: ./expressjs-backend/package.json
          action: rebuild
        - path: ./expressjs-backend
          target: /src
          ignore:
            - ./expressjs-backend/node_modules
            - ./expressjs-backend/.git
          action: rebuild

  catering_nextjs:
    container_name: online-catering-reservation-system-nextjs
    image: drey34/catering-nextjs-frontend:1.0
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - catering_api
    env_file:
      - ./nextjs-frontend/.env.development.local # Load environment variables from this file
    command: npm run dev # Ensure your dev script is set up to watch changes
    develop:
      watch:
        - path: ./nextjs-frontend/package-lock.json
          action: rebuild
        - path: ./nextjs-frontend/package.json
          action: rebuild
        - path: ./nextjs-frontend
          target: /src
          ignore:
            - ./nextjs-frontend/node_modules
            - ./nextjs-frontend/.git
          action: rebuild

volumes:
  mongo_db: {}
