import type {
  CateringPackage,
  PlatedPackage,
  EventPackage,
  EventType,
  FormStepType,
} from "@/types/customer/package-types";

// Define buffet packages
export const buffetPackages: CateringPackage[] = [
  {
    id: "buffet-a",
    name: "Set A - Basic Feast",
    description:
      "A simple yet satisfying selection of Filipino favorites for small gatherings.",
    pricePerPax: 350,
    minimumPax: 20,
    recommendedPax: 30,
    maximumPax: 50,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Basic table setup",
      "Disposable utensils and plates",
      "Service staff (2 personnel)",
      "Food warmers and serving utensils",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "buffet-b",
    name: "Set B - Family Celebration",
    description:
      "A hearty selection of dishes perfect for family celebrations and small parties.",
    pricePerPax: 450,
    minimumPax: 30,
    recommendedPax: 50,
    maximumPax: 80,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Enhanced table setup",
      "Disposable utensils and plates",
      "Service staff (3 personnel)",
      "Food warmers and serving utensils",
      "Basic dessert station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "buffet-c",
    name: "Set C - Fiesta Favorites",
    description:
      "A complete Filipino fiesta experience with a wide variety of traditional dishes.",
    pricePerPax: 550,
    minimumPax: 50,
    recommendedPax: 80,
    maximumPax: 120,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Premium table setup",
      "Quality disposable utensils and plates",
      "Service staff (4 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 2 options",
      "Welcome drinks",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "buffet-d",
    name: "Set D - Premium Celebration",
    description:
      "An elevated dining experience featuring premium Filipino dishes for special occasions.",
    pricePerPax: 650,
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Seafood", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: true },
    ],
    inclusions: [
      "Elegant table setup with centerpieces",
      "Quality disposable utensils and plates",
      "Service staff (5 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 3 options",
      "Welcome drinks and iced tea",
      "Basic coffee station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "buffet-e",
    name: "Set E - Grand Feast",
    description:
      "A grand Filipino feast featuring a comprehensive selection of dishes for large celebrations.",
    pricePerPax: 750,
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 200,
    options: [
      { category: "Soup", count: 2, required: true },
      { category: "Salad", count: 2, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 2, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Seafood", count: 1, required: true },
      { category: "Vegetable", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Dessert", count: 2, required: true },
      { category: "Beverage", count: 2, required: true },
    ],
    inclusions: [
      "Premium table setup with floral arrangements",
      "Quality disposable utensils and plates",
      "Service staff (7 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 4 options",
      "Welcome drinks and unlimited iced tea",
      "Coffee and tea station",
      "Fruit station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "buffet-f",
    name: "Set F - Royal Filipino Banquet",
    description:
      "The ultimate Filipino banquet experience featuring our finest dishes and premium service.",
    pricePerPax: 950,
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    options: [
      { category: "Soup", count: 2, required: true },
      { category: "Salad", count: 2, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 2, required: true },
      { category: "Beef", count: 2, required: true },
      { category: "Seafood", count: 2, required: true },
      { category: "Vegetable", count: 2, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Dessert", count: 3, required: true },
      { category: "Beverage", count: 3, required: true },
    ],
    inclusions: [
      "Luxury table setup with premium decorations",
      "Fine dining utensils and plates",
      "Service staff (10 personnel)",
      "Food warmers and serving utensils",
      "Premium dessert station with 5 options",
      "Welcome cocktails and unlimited beverages",
      "Premium coffee and tea station",
      "Fruit and cheese station",
      "Live cooking station",
      "Ice cream station",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
];

// Define plated packages as separate data
export const platedPackages: PlatedPackage[] = [
  {
    id: "plated-a",
    name: "Plated Set A - Basic Feast",
    description:
      "A simple yet satisfying selection of Filipino favorites for small gatherings. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 450, // 350 + (4 * 100) / 20
    minimumPax: 20,
    recommendedPax: 30,
    maximumPax: 50,
    serviceHours: 4,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Basic table setup",
      "Disposable utensils and plates",
      "Service staff (2 personnel)",
      "Food warmers and serving utensils",
      "4 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "plated-b",
    name: "Plated Set B - Family Celebration",
    description:
      "A hearty selection of dishes perfect for family celebrations and small parties. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 567, // 450 + (4.5 * 100) / 30
    minimumPax: 30,
    recommendedPax: 50,
    maximumPax: 80,
    serviceHours: 4.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Enhanced table setup",
      "Disposable utensils and plates",
      "Service staff (3 personnel)",
      "Food warmers and serving utensils",
      "Basic dessert station",
      "4.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "plated-c",
    name: "Plated Set C - Fiesta Favorites",
    description:
      "A complete Filipino fiesta experience with a wide variety of traditional dishes. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 660, // 550 + (5 * 100) / 50
    minimumPax: 50,
    recommendedPax: 80,
    maximumPax: 120,
    serviceHours: 5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 1, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: false },
    ],
    inclusions: [
      "Premium table setup",
      "Quality disposable utensils and plates",
      "Service staff (4 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 2 options",
      "Welcome drinks",
      "5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "plated-d",
    name: "Plated Set D - Premium Celebration",
    description:
      "An elevated dining experience featuring premium Filipino dishes for special occasions. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 760, // 650 + (5.5 * 100) / 50
    minimumPax: 50,
    recommendedPax: 100,
    maximumPax: 150,
    serviceHours: 5.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 1, required: true },
      { category: "Salad", count: 1, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 1, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Seafood", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Beverage", count: 1, required: true },
    ],
    inclusions: [
      "Elegant table setup with centerpieces",
      "Quality disposable utensils and plates",
      "Service staff (5 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 3 options",
      "Welcome drinks and iced tea",
      "Basic coffee station",
      "5.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "plated-e",
    name: "Plated Set E - Grand Feast",
    description:
      "A grand Filipino feast featuring a comprehensive selection of dishes for large celebrations. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 857, // 750 + (6 * 100) / 80
    minimumPax: 80,
    recommendedPax: 120,
    maximumPax: 200,
    serviceHours: 6,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 2, required: true },
      { category: "Salad", count: 2, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 2, required: true },
      { category: "Beef", count: 1, required: true },
      { category: "Seafood", count: 1, required: true },
      { category: "Vegetable", count: 1, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Dessert", count: 2, required: true },
      { category: "Beverage", count: 2, required: true },
    ],
    inclusions: [
      "Premium table setup with floral arrangements",
      "Quality disposable utensils and plates",
      "Service staff (7 personnel)",
      "Food warmers and serving utensils",
      "Dessert station with 4 options",
      "Welcome drinks and unlimited iced tea",
      "Coffee and tea station",
      "Fruit station",
      "6 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "plated-f",
    name: "Plated Set F - Royal Filipino Banquet",
    description:
      "The ultimate Filipino banquet experience featuring our finest dishes and premium service. Served directly to your guests' tables by our professional staff.",
    pricePerPax: 1067, // 950 + (6.5 * 100) / 100
    minimumPax: 100,
    recommendedPax: 150,
    maximumPax: 300,
    serviceHours: 6.5,
    serviceCharge: 100,
    options: [
      { category: "Soup", count: 2, required: true },
      { category: "Salad", count: 2, required: true },
      { category: "Chicken", count: 2, required: true },
      { category: "Pork", count: 2, required: true },
      { category: "Beef", count: 2, required: true },
      { category: "Seafood", count: 2, required: true },
      { category: "Vegetable", count: 2, required: true },
      { category: "Noodle", count: 1, required: true },
      { category: "Dessert", count: 3, required: true },
      { category: "Beverage", count: 3, required: true },
    ],
    inclusions: [
      "Luxury table setup with premium decorations",
      "Fine dining utensils and plates",
      "Service staff (10 personnel)",
      "Food warmers and serving utensils",
      "Premium dessert station with 5 options",
      "Welcome cocktails and unlimited beverages",
      "Premium coffee and tea station",
      "Fruit and cheese station",
      "Live cooking station",
      "Ice cream station",
      "6.5 hours of table service",
      "Professional waitstaff",
      "Table-side service",
      "Course-by-course serving",
    ],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
];

// Define event types
export const eventTypes: EventType[] = [
  "Birthday",
  "Wedding",
  "Corporate",
  "Graduation",
];

// Define event packages
export const eventPackages: Record<EventType, EventPackage[]> = {
  Birthday: [
    {
      id: "birthday-a",
      name: "Birthday Celebration - Basic",
      description:
        "A fun and festive package perfect for birthday celebrations.",
      eventType: "Birthday",
      pricePerPax: 450,
      minimumPax: 30,
      serviceHours: 4,
      options: [
        { category: "Soup", count: 1, required: true },
        { category: "Salad", count: 1, required: true },
        { category: "Chicken", count: 1, required: true },
        { category: "Pork", count: 1, required: true },
        { category: "Noodle", count: 1, required: true },
        { category: "Dessert", count: 1, required: true },
        { category: "Beverage", count: 1, required: true },
      ],
      inclusions: [
        "Unlimited steamed rice",
        "Basic birthday setup",
        "Disposable utensils and plates",
        "Service staff (3 personnel)",
        "Food warmers and serving utensils",
        "Birthday cake table setup",
        "Welcome drinks",
      ],
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    // More birthday packages...
  ],
  Wedding: [
    {
      id: "wedding-a",
      name: "Wedding Reception - Essential",
      description:
        "An essential wedding reception package for intimate celebrations.",
      eventType: "Wedding",
      pricePerPax: 550,
      minimumPax: 50,
      serviceHours: 4,
      options: [
        { category: "Soup", count: 1, required: true },
        { category: "Salad", count: 1, required: true },
        { category: "Chicken", count: 1, required: true },
        { category: "Pork", count: 1, required: true },
        { category: "Beef", count: 1, required: true },
        { category: "Noodle", count: 1, required: true },
        { category: "Dessert", count: 1, required: true },
        { category: "Beverage", count: 1, required: true },
      ],
      inclusions: [
        "Unlimited steamed rice",
        "Basic wedding reception setup",
        "Quality disposable utensils and plates",
        "Service staff (4 personnel)",
        "Food warmers and serving utensils",
        "Cake table setup",
        "Welcome drinks",
        "Basic toast setup",
      ],
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    // More wedding packages...
  ],
  Corporate: [
    {
      id: "corporate-a",
      name: "Corporate Event - Basic",
      description:
        "A basic corporate event package suitable for meetings and small gatherings.",
      eventType: "Corporate",
      pricePerPax: 450,
      minimumPax: 30,
      serviceHours: 4,
      options: [
        { category: "Soup", count: 1, required: true },
        { category: "Salad", count: 1, required: true },
        { category: "Chicken", count: 1, required: true },
        { category: "Pork", count: 1, required: true },
        { category: "Noodle", count: 1, required: true },
        { category: "Dessert", count: 1, required: true },
        { category: "Beverage", count: 1, required: true },
      ],
      inclusions: [
        "Unlimited steamed rice",
        "Basic corporate setup",
        "Quality disposable utensils and plates",
        "Service staff (3 personnel)",
        "Food warmers and serving utensils",
        "Water station",
        "Basic coffee and tea station",
      ],
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    // More corporate packages...
  ],
  Graduation: [
    {
      id: "graduation-a",
      name: "Graduation Celebration - Basic",
      description:
        "A basic graduation celebration package for the new graduate.",
      eventType: "Graduation",
      pricePerPax: 400,
      minimumPax: 30,
      serviceHours: 4,
      options: [
        { category: "Soup", count: 1, required: true },
        { category: "Salad", count: 1, required: true },
        { category: "Chicken", count: 1, required: true },
        { category: "Pork", count: 1, required: true },
        { category: "Noodle", count: 1, required: true },
        { category: "Dessert", count: 1, required: true },
        { category: "Beverage", count: 1, required: true },
      ],
      inclusions: [
        "Unlimited steamed rice",
        "Basic graduation setup",
        "Quality disposable utensils and plates",
        "Service staff (3 personnel)",
        "Food warmers and serving utensils",
        "Graduation cake table setup",
        "Welcome drinks",
      ],
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    // More graduation packages...
  ],
};

// Custom Package Form Steps
export const formSteps: FormStepType[] = [
  {
    id: "customer-info",
    title: "Customer Information",
    description: "Please provide your contact details",
  },
  {
    id: "event-details",
    title: "Event Details",
    description: "Tell us about your event",
  },
  {
    id: "menu-selection",
    title: "Menu Selection",
    description: "Choose your preferred dishes",
  },
  {
    id: "review",
    title: "Review",
    description: "Review your custom package",
  },
];

// Booking steps
export const bookingSteps: FormStepType[] = [
  {
    id: "customer-info",
    title: "Customer Information",
    description: "Please provide your contact details",
  },
  {
    id: "event-details",
    title: "Event Details",
    description: "Tell us about your event",
  },
  {
    id: "package-selection",
    title: "Package Selection",
    description: "Review your selected package and add any special requests",
  },
  {
    id: "review",
    title: "Review",
    description: "Review your booking details",
  },
];
