const menuItems = [
  {
    id: 1,
    name: "Grilled Chicken with Herbs",
    category: "Main",
    price: 15.99,
    description:
      "Tender chicken breast marinated with fresh herbs and grilled to perfection.",
    ingredients: "Chicken breast, rosemary, thyme, olive oil, garlic",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Mar 07, 2025",
    timesOrdered: 24,
    inPackages: 3,
    rating: 4,
    likes: 12500,
  },
  {
    id: 2,
    name: "Caprese Salad",
    category: "Appetizer",
    price: 8.99,
    description:
      "Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.",
    ingredients: "Mozzarella, tomatoes, basil, balsamic glaze, olive oil",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Mar 05, 2025",
    timesOrdered: 18,
    inPackages: 2,
    rating: 5,
    likes: 12500,
  },
  {
    id: 3,
    name: "Chocolate Mousse",
    category: "Dessert",
    price: 7.5,
    description: "Rich and creamy chocolate mousse topped with whipped cream.",
    ingredients: "Dark chocolate, heavy cream, eggs, sugar, vanilla extract",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Feb 28, 2025",
    timesOrdered: 32,
    inPackages: 4,
    rating: 4,
    likes: 12500,
  },
  {
    id: 4,
    name: "Vegetable Risotto",
    category: "Main",
    price: 13.99,
    description:
      "Creamy arborio rice cooked with seasonal vegetables and parmesan cheese.",
    ingredients:
      "Arborio rice, vegetable stock, parmesan, asparagus, mushrooms",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Mar 02, 2025",
    timesOrdered: 15,
    inPackages: 2,
    rating: 3,
    likes: 12500,
  },
  {
    id: 5,
    name: "Shrimp Cocktail",
    category: "Appetizer",
    price: 12.5,
    description: "Chilled jumbo shrimp served with zesty cocktail sauce.",
    ingredients: "Jumbo shrimp, cocktail sauce, lemon, parsley",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Mar 01, 2025",
    timesOrdered: 22,
    inPackages: 3,
    rating: 5,
    likes: 12500,
  },
  {
    id: 6,
    name: "Tiramisu",
    category: "Dessert",
    price: 8.99,
    description:
      "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    ingredients: "Ladyfingers, mascarpone, coffee, cocoa powder, eggs",
    image: "/placeholder.svg?height=300&width=300",
    lastUpdated: "Feb 25, 2025",
    timesOrdered: 28,
    inPackages: 3,
    rating: 4,
    likes: 12500,
  },
];

const selectorItems = [
  { value: "default", title: "Default" },
  { value: "name-asc", title: "Name (A-Z)" },
  { value: "name-desc", title: "Name (Z-A)" },
  { value: "price-asc", title: "Price (Low - High)" },
  { value: "price-desc", title: "Price (High - Low)" },
  { value: "ordered-desc", title: "Most Ordered" },
  { value: "ordered-asc", title: "Least Ordered" },
];
export { menuItems, selectorItems };
