import { ReservationItem } from "@/types/reservation-types";
import { PaxArrayType } from "@/types/reservation-types";

// Example SelectedMenus for demo purposes
const exampleSelectedMenus = {
  menu1: {
    servingSize1: {
      quantity: 2,
      paxSelected: "4-6 pax" as PaxArrayType,
      pricePerPax: 250,
    },
  },
  menu2: {
    servingSize1: {
      quantity: 1,
      paxSelected: "8-10 pax" as PaxArrayType,
      pricePerPax: 400,
    },
  },
};

export const reservations: ReservationItem[] = [
  {
    fullName: "Juan Dela Cruz",
    email: "juan.delacruz@example.com",
    contactNumber: "09171234567",
    reservationType: "event",
    eventType: "Birthday",
    reservationDate: new Date("2025-05-01T10:00:00"),
    reservationTime: "10:00",
    period: "A.M.",
    guestCount: 50,
    venue: "Grand Ballroom",
    cateringOptions: "event",
    serviceType: "Buffet",
    serviceFee: 1500,
    serviceHours: "4",
    selectedPackage: "Gold",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 25000,
    specialRequests: "Vegetarian options included",
    deliveryOption: "Delivery",
    deliveryFee: 500,
    deliveryAddress: "123 Main St, Cityville",
    deliveryInstructions: "Please arrive 30 minutes early",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Maria Santos",
    email: "maria.santos@example.com",
    contactNumber: "09181234567",
    reservationType: "personal",
    eventType: "",
    reservationDate: new Date("2025-05-03T18:00:00"),
    reservationTime: "18:00",
    period: "P.M.",
    guestCount: 20,
    venue: "Home",
    cateringOptions: "custom",
    serviceType: "Buffet",
    serviceFee: 500,
    serviceHours: "2",
    selectedPackage: "Silver",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 7000,
    specialRequests: "No seafood",
    deliveryOption: "Pickup",
    deliveryFee: 0,
    deliveryAddress: "",
    deliveryInstructions: "",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Pedro Pascual",
    email: "pedro.pascual@example.com",
    contactNumber: "09221234567",
    reservationType: "event",
    eventType: "Wedding",
    reservationDate: new Date("2025-06-10T16:00:00"),
    reservationTime: "16:00",
    period: "P.M.",
    guestCount: 100,
    venue: "Beach Resort",
    cateringOptions: "event",
    serviceType: "Plated",
    serviceFee: 3000,
    serviceHours: "6",
    selectedPackage: "Diamond",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 80000,
    specialRequests: "Outdoor setup",
    deliveryOption: "Delivery",
    deliveryFee: 2000,
    deliveryAddress: "456 Beach Rd, Baytown",
    deliveryInstructions: "Set up near the stage",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Ana Rivera",
    email: "ana.rivera@example.com",
    contactNumber: "09331234567",
    reservationType: "personal",
    eventType: "",
    reservationDate: new Date("2025-05-15T12:00:00"),
    reservationTime: "12:00",
    period: "P.M.",
    guestCount: 10,
    venue: "Office",
    cateringOptions: "custom",
    serviceType: "Buffet",
    serviceFee: 0,
    serviceHours: "1",
    selectedPackage: "Bronze",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 3000,
    specialRequests: "Gluten-free dessert",
    deliveryOption: "Pickup",
    deliveryFee: 0,
    deliveryAddress: "",
    deliveryInstructions: "",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Carlos Tan",
    email: "carlos.tan@example.com",
    contactNumber: "09441234567",
    reservationType: "event",
    eventType: "Corporate Meeting",
    reservationDate: new Date("2025-07-01T09:00:00"),
    reservationTime: "09:00",
    period: "A.M.",
    guestCount: 30,
    venue: "Conference Hall",
    cateringOptions: "event",
    serviceType: "Buffet",
    serviceFee: 1000,
    serviceHours: "3",
    selectedPackage: "Corporate",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 12000,
    specialRequests: "Coffee station included",
    deliveryOption: "Delivery",
    deliveryFee: 300,
    deliveryAddress: "789 Office Park, Workcity",
    deliveryInstructions: "Set up at the back",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Liza Cruz",
    email: "liza.cruz@example.com",
    contactNumber: "09551234567",
    reservationType: "personal",
    eventType: "",
    reservationDate: new Date("2025-06-20T11:00:00"),
    reservationTime: "11:00",
    period: "A.M.",
    guestCount: 8,
    venue: "Apartment",
    cateringOptions: "custom",
    serviceType: "Buffet",
    serviceFee: 0,
    serviceHours: "1",
    selectedPackage: "Bronze",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 2500,
    specialRequests: "No pork",
    deliveryOption: "Pickup",
    deliveryFee: 0,
    deliveryAddress: "",
    deliveryInstructions: "",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Mark Lee",
    email: "mark.lee@example.com",
    contactNumber: "09661234567",
    reservationType: "event",
    eventType: "Anniversary",
    reservationDate: new Date("2025-08-05T19:00:00"),
    reservationTime: "19:00",
    period: "P.M.",
    guestCount: 40,
    venue: "Banquet Hall",
    cateringOptions: "event",
    serviceType: "Plated",
    serviceFee: 2000,
    serviceHours: "4",
    selectedPackage: "Gold",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 32000,
    specialRequests: "Live band setup",
    deliveryOption: "Delivery",
    deliveryFee: 800,
    deliveryAddress: "321 Party Ave, Festivity",
    deliveryInstructions: "Stage left",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Grace Lim",
    email: "grace.lim@example.com",
    contactNumber: "09771234567",
    reservationType: "personal",
    eventType: "",
    reservationDate: new Date("2025-09-12T13:00:00"),
    reservationTime: "13:00",
    period: "P.M.",
    guestCount: 15,
    venue: "Home",
    cateringOptions: "custom",
    serviceType: "Buffet",
    serviceFee: 0,
    serviceHours: "2",
    selectedPackage: "Silver",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 5000,
    specialRequests: "Extra drinks",
    deliveryOption: "Pickup",
    deliveryFee: 0,
    deliveryAddress: "",
    deliveryInstructions: "",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Ramon Reyes",
    email: "ramon.reyes@example.com",
    contactNumber: "09881234567",
    reservationType: "event",
    eventType: "Debut",
    reservationDate: new Date("2025-10-10T17:00:00"),
    reservationTime: "17:00",
    period: "P.M.",
    guestCount: 60,
    venue: "Event Center",
    cateringOptions: "event",
    serviceType: "Buffet",
    serviceFee: 1800,
    serviceHours: "5",
    selectedPackage: "Platinum",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 40000,
    specialRequests: "Photo booth",
    deliveryOption: "Delivery",
    deliveryFee: 1000,
    deliveryAddress: "654 Debut St, Celebration",
    deliveryInstructions: "Main entrance",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
  {
    fullName: "Sofia Gomez",
    email: "sofia.gomez@example.com",
    contactNumber: "09991234567",
    reservationType: "personal",
    eventType: "",
    reservationDate: new Date("2025-11-15T15:00:00"),
    reservationTime: "15:00",
    period: "P.M.",
    guestCount: 12,
    venue: "Condo",
    cateringOptions: "custom",
    serviceType: "Buffet",
    serviceFee: 0,
    serviceHours: "1",
    selectedPackage: "Bronze",
    selectedMenus: exampleSelectedMenus,
    totalPrice: 3500,
    specialRequests: "Vegan menu",
    deliveryOption: "Pickup",
    deliveryFee: 0,
    deliveryAddress: "",
    deliveryInstructions: "",
    status: "Pending",
    createdAt: new Date("2025-04-25T09:00:00"),
    updatedAt: new Date("2025-04-26T09:00:00"),
  },
];
