import { MenuItem } from "@/types/menu-types";

export const menuItems: MenuItem[] = [
  {
    name: "Chicken Soup",
    category: "Soup",
    available: true,
    spicy: false,
    shortDescription: "A warm and hearty chicken broth with vegetables.",
    fullDescription:
      "Our Chicken Soup is made from fresh chicken, carrots, celery, and potatoes, simmered in a savory broth. Perfect for any occasion.",
    ingredients: ["Chicken", "Carrots", "Celery", "Potatoes", "Chicken Broth"],
    allergens: ["None"],
    preparationMethod: "Simmer the chicken and vegetables in broth for 1 hour.",
    regularPricePerPax: 150,
    prices: [
      //write your own
      { minimumPax: 4, maximumPax: 6, price: 150, discount: 3 },
      { minimumPax: 8, maximumPax: 10, price: 150, discount: 6 },
      { minimumPax: 13, maximumPax: 15, price: 150, discount: 9 },
      { minimumPax: 18, maximumPax: 20, price: 150, discount: 14 },
    ],
    imageUrl:
      "https://www.allrecipes.com/thmb/IhQhEfMAeIRupmvXn6DYrfF9zNs=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8814-homemade-chicken-soup-DDMFS-beauty-4x3-31640-924adc63a78543a7822c5704727f6e4b.jpg",
    perServing: "250g",
    nutritionInfo: {
      calories: "200 kcal",
      protein: "15 g",
      fat: "7 g",
      carbs: "20 g",
      sodium: "800 mg",
      fiber: "2 g",
      sugar: "4 g",
      cholesterol: "30 mg",
    },
  },
  {
    name: "Caesar Salad",
    category: "Salad",
    available: true,
    spicy: false,
    shortDescription: "A crisp romaine salad with Caesar dressing.",
    fullDescription:
      "Classic Caesar Salad made with romaine lettuce, croutons, parmesan cheese, and creamy dressing.",
    ingredients: [
      "Romaine Lettuce",
      "Croutons",
      "Parmesan Cheese",
      "Caesar Dressing",
    ],
    allergens: ["Milk", "Eggs", "Wheat"],
    preparationMethod:
      "Toss all ingredients with dressing just before serving.",
    regularPricePerPax: 120,
    prices: [
      { minimumPax: 4, maximumPax: 6, price: 120, discount: 3 },
      { minimumPax: 8, maximumPax: 10, price: 120, discount: 6 },
      { minimumPax: 13, maximumPax: 15, price: 120, discount: 9 },
      { minimumPax: 18, maximumPax: 20, price: 120, discount: 14 },
    ],
    imageUrl:
      "https://www.allrecipes.com/thmb/9PC5mJkK4D_AjwNnllhWNn2c3z0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Classic-Caesar-Salad-2000-6b3bd6e156f84d1ab5e776702bd48a15.jpg",
    perServing: "180g",
    nutritionInfo: {
      calories: "300 kcal",
      protein: "8 g",
      fat: "20 g",
      carbs: "20 g",
      sodium: "600 mg",
      fiber: "3 g",
      sugar: "2 g",
      cholesterol: "30 mg",
    },
  },
  {
    name: "Beef Steak",
    category: "Beef",
    available: true,
    spicy: true,
    shortDescription: "Grilled beef steak with a spicy marinade.",
    fullDescription:
      "Tender beef steak marinated with spices, grilled and served with sides.",
    ingredients: [
      "Beef",
      "Garlic",
      "Black Pepper",
      "Chili",
      "Mashed Potatoes",
      "Vegetables",
    ],
    allergens: ["None"],
    preparationMethod: "Marinate and grill beef to desired doneness.",
    regularPricePerPax: 350,
    prices: [
      { minimumPax: 4, maximumPax: 6, price: 350, discount: 3 },
      { minimumPax: 8, maximumPax: 10, price: 350, discount: 6 },
      { minimumPax: 13, maximumPax: 15, price: 350, discount: 9 },
      { minimumPax: 18, maximumPax: 20, price: 350, discount: 14 },
    ],
    imageUrl:
      "https://www.allrecipes.com/thmb/y0mi096UlTi7GNu_aIvl4qt2Of0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/212911-filipino-beef-steak-ddmfs-3X4-0284-ac57852ee0d54c8e875846c096effb3c.jpg",
    perServing: "300g",
    nutritionInfo: {
      calories: "450 kcal",
      protein: "30 g",
      fat: "30 g",
      carbs: "15 g",
      sodium: "600 mg",
      fiber: "3 g",
      sugar: "4 g",
      cholesterol: "80 mg",
    },
  },
  // {
  //   name: "Pork Adobo",
  //   category: "Pork",
  //   available: true,
  //   spicy: false,
  //   shortDescription: "Classic Filipino soy-vinegar braised pork.",
  //   fullDescription:
  //     "Tender pork belly slow-braised in soy sauce, vinegar, and spices.",
  //   ingredients: [
  //     "Pork Belly",
  //     "Soy Sauce",
  //     "Vinegar",
  //     "Garlic",
  //     "Bay Leaves",
  //     "Peppercorns",
  //   ],
  //   allergens: ["Soybeans", "Gluten"],
  //   preparationMethod: "Simmer pork with marinade until tender and flavorful.",
  //   regularPricePerPax: 180,
  //   prices: [
  //     { minimumPax: 4, maximumPax: 6, price: 180, discount: 3 },
  //     { minimumPax: 8, maximumPax: 10, price: 180, discount: 6 },
  //     { minimumPax: 13, maximumPax: 15, price: 180, discount: 9 },
  //     { minimumPax: 18, maximumPax: 20, price: 180, discount: 14 },
  //   ],
  //   imageUrl: "https://example.com/pork-adobo.jpg",
  //   perServing: "250g",
  //   nutritionInfo: {
  //     calories: "350 kcal",
  //     protein: "25 g",
  //     fat: "22 g",
  //     carbs: "10 g",
  //     sodium: "800 mg",
  //     fiber: "1 g",
  //     sugar: "2 g",
  //     cholesterol: "60 mg",
  //   },
  // },
  {
    name: "Seafood Paella",
    category: "Seafood",
    available: true,
    spicy: false,
    shortDescription: "Traditional Spanish rice dish with seafood.",
    fullDescription:
      "Rich and colorful paella cooked with shrimp, mussels, and squid, infused with saffron and herbs.",
    ingredients: [
      "Rice",
      "Shrimp",
      "Mussels",
      "Squid",
      "Saffron",
      "Bell Peppers",
      "Tomatoes",
    ],
    allergens: ["Shellfish", "Fish"],
    preparationMethod: "Cook rice and seafood together in a large pan.",
    regularPricePerPax: 250,
    prices: [
      { minimumPax: 4, maximumPax: 6, price: 250, discount: 3 },
      { minimumPax: 8, maximumPax: 10, price: 250, discount: 6 },
      { minimumPax: 13, maximumPax: 15, price: 250, discount: 9 },
      { minimumPax: 18, maximumPax: 20, price: 250, discount: 14 },
    ],
    imageUrl:
      "https://www.allrecipes.com/thmb/bY90fVhFITJplYbynjp-iclBPhQ=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8727168_Seafood-Paella_Dotdash-Meredith-Food-Studios_4x3-061a6a5e3eb743bf95272854a2e4e62b.jpg",
    perServing: "280g",
    nutritionInfo: {
      calories: "400 kcal",
      protein: "30 g",
      fat: "12 g",
      carbs: "50 g",
      sodium: "900 mg",
      fiber: "5 g",
      sugar: "5 g",
      cholesterol: "70 mg",
    },
  },
];
