import { MenuItem } from "@/types/customer/menu-types";

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: "Herb-Crusted Prime Rib",
    category: "Pork",
    available: true,
    shortDescription: "Slow-roasted prime rib with a fragrant herb crust",
    fullDescription:
      "Our signature prime rib is slow-roasted for 12 hours to achieve perfect tenderness. The exterior is coated with a blend of fresh herbs and spices that create a flavorful crust, complemented by our house-made au jus. Each slice is carefully carved to preserve the juicy interior while maintaining the aromatic herb crust that has become our hallmark. The prime rib is sourced from premium grass-fed cattle, ensuring exceptional marbling and flavor in every bite.",
    ingredients: [
      "Prime rib",
      "Rosemary",
      "Thyme",
      "Garlic",
      "Black pepper",
      "Sea salt",
      "Olive oil",
      "Dijon mustard",
    ],
    allergens: ["None"],
    preparationMethod:
      "Slow-roasted at low temperature for 12 hours, rested, then finished at high heat to create a perfect crust.",
    prices: {
      30: 899.99,
      50: 1399.99,
      100: 2599.99,
    },
    regularPricePerPax: 39.99,
    imageUrl:
      "https://images.unsplash.com/photo-1558030006-450675393462?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1769&q=80",
    rating: 4.8,
    ratingCount: 124,
    spicy: false,
    nutritionalInfo: {
      Calories: "320 kcal",
      Protein: "28g",
      Fat: "24g",
      Carbs: "2g",
      Sodium: "580mg",
      Fiber: "0g",
      Sugar: "0g",
      Cholesterol: "85mg",
    },
  },
  {
    id: 2,
    name: "Truffle Mushroom Risotto",
    category: "Chicken",
    available: true,
    shortDescription: "Creamy Arborio rice with wild mushrooms and truffle oil",
    fullDescription:
      "A luxurious vegetarian option featuring Arborio rice slowly cooked to creamy perfection with a medley of wild mushrooms, finished with truffle oil and aged Parmesan cheese. Each grain of rice is cooked to al dente perfection, maintaining its structure while absorbing the rich flavors of our house-made mushroom stock. The earthy aroma of truffle oil elevates this classic dish to new heights of culinary excellence.",
    ingredients: [
      "Arborio rice",
      "Wild mushroom blend",
      "Shallots",
      "White wine",
      "Vegetable stock",
      "Truffle oil",
      "Parmesan cheese",
      "Fresh thyme",
    ],
    allergens: ["Dairy"],
    preparationMethod:
      "Traditional risotto method with constant stirring and gradual addition of warm stock to develop the perfect creamy texture.",
    prices: {
      30: 599.99,
      50: 899.99,
      100: 1699.99,
    },
    regularPricePerPax: 24.99,
    imageUrl:
      "https://images.unsplash.com/photo-1633964913295-ceb43826e7c7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    rating: 4.6,
    ratingCount: 98,
    spicy: false,
    nutritionalInfo: {
      Calories: "380 kcal",
      Protein: "8g",
      Fat: "18g",
      Carbs: "42g",
      Sodium: "420mg",
      Fiber: "3g",
      Sugar: "2g",
      Cholesterol: "15mg",
    },
  },
  {
    id: 3,
    name: "Seared Scallops with Champagne Sauce",
    category: "Beverage",
    available: false,
    shortDescription:
      "Perfectly seared scallops with a delicate champagne reduction",
    fullDescription:
      "Jumbo sea scallops are seared to golden perfection and served with a delicate champagne and butter sauce. Garnished with micro greens and edible flowers for an elegant presentation. Our chefs take great care to achieve the perfect caramelization on each scallop while maintaining a tender, translucent center. The champagne sauce is reduced slowly to concentrate its flavors while maintaining the delicate notes of the premium champagne we use.",
    ingredients: [
      "Jumbo sea scallops",
      "Champagne",
      "Shallots",
      "Heavy cream",
      "Unsalted butter",
      "Lemon zest",
      "Micro greens",
      "Edible flowers",
    ],
    allergens: ["Shellfish", "Dairy"],
    preparationMethod:
      "Scallops are pat dry and seared at high heat to achieve caramelization while maintaining a tender center. The sauce is prepared separately and spooned over just before serving.",
    prices: {
      30: 799.99,
      50: 1299.99,
      100: 2399.99,
    },
    regularPricePerPax: 34.99,
    imageUrl:
      "https://images.unsplash.com/photo-1599021456807-25db0f974333?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    rating: 4.9,
    ratingCount: 76,
    spicy: false,
    nutritionalInfo: {
      Calories: "290 kcal",
      Protein: "22g",
      Fat: "19g",
      Carbs: "8g",
      Sodium: "520mg",
      Fiber: "0g",
      Sugar: "2g",
      Cholesterol: "65mg",
    },
  },
  {
    id: 4,
    name: "Duck Confit with Cherry Reduction",
    category: "Chicken",
    available: true,
    shortDescription: "Tender duck leg confit with a tart-sweet cherry sauce",
    fullDescription:
      "Duck legs slowly cooked in their own fat until meltingly tender, served with a reduction of tart cherries and port wine. Accompanied by crispy duck fat potatoes and seasonal vegetables. The duck is cured with our proprietary blend of spices for 24 hours before being submerged in duck fat and cooked at a precisely controlled low temperature. This traditional French technique results in meat that is incredibly tender and full of flavor.",
    ingredients: [
      "Duck legs",
      "Duck fat",
      "Tart cherries",
      "Port wine",
      "Thyme",
      "Garlic",
      "Fingerling potatoes",
      "Seasonal vegetables",
    ],
    allergens: ["None"],
    preparationMethod:
      "Traditional confit method where duck legs are cured overnight, then slowly cooked in duck fat at low temperature for 6-8 hours until tender.",
    prices: {
      30: 849.99,
      50: 1349.99,
      100: 2499.99,
    },
    regularPricePerPax: 36.99,
    imageUrl:
      "https://images.unsplash.com/photo-1580554530778-ca36943938b2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    rating: 4.7,
    ratingCount: 112,
    spicy: false,
    nutritionalInfo: {
      Calories: "420 kcal",
      Protein: "32g",
      Fat: "28g",
      Carbs: "12g",
      Sodium: "640mg",
      Fiber: "2g",
      Sugar: "8g",
      Cholesterol: "95mg",
    },
  },
  {
    id: 5,
    name: "Lobster Thermidor",
    category: "Seafood",
    available: true,
    shortDescription: "Classic lobster dish with a rich brandy cream sauce",
    fullDescription:
      "A timeless delicacy featuring lobster meat in a creamy sauce flavored with brandy, mustard, and tarragon, topped with Gruyère cheese and broiled until golden. We use only the finest Maine lobsters, which are steamed to perfection before the meat is carefully removed and incorporated into our signature sauce. The dish is finished under the broiler to create a golden, bubbling crust that adds a delightful textural contrast.",
    ingredients: [
      "Maine lobster",
      "Brandy",
      "Dijon mustard",
      "Heavy cream",
      "Tarragon",
      "Shallots",
      "Gruyère cheese",
      "Butter",
    ],
    allergens: ["Shellfish", "Dairy", "Alcohol"],
    preparationMethod:
      "Lobsters are steamed, meat is removed and sautéed with aromatics, then combined with a brandy-infused béchamel sauce, returned to the shells, topped with cheese and broiled.",
    prices: {
      30: 1299.99,
      50: 1999.99,
      100: 3799.99,
    },
    regularPricePerPax: 54.99,
    imageUrl:
      "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
    rating: 4.9,
    ratingCount: 145,
    spicy: false,
    nutritionalInfo: {
      Calories: "480 kcal",
      Protein: "36g",
      Fat: "32g",
      Carbs: "10g",
      Sodium: "720mg",
      Fiber: "0g",
      Sugar: "2g",
      Cholesterol: "180mg",
    },
  },
  {
    id: 6,
    name: "Spicy Thai Curry",
    category: "Chicken",
    available: true,
    shortDescription: "Aromatic curry with lemongrass, chili, and coconut milk",
    fullDescription:
      "A vibrant and aromatic Thai curry featuring a perfect balance of spicy, sweet, and savory flavors. Our chef's special blend of Thai chilies, lemongrass, galangal, and kaffir lime leaves creates an authentic base, while coconut milk adds a rich creaminess that tempers the heat. Served with fragrant jasmine rice and garnished with fresh Thai basil and lime wedges.",
    ingredients: [
      "Thai chilies",
      "Lemongrass",
      "Galangal",
      "Kaffir lime leaves",
      "Coconut milk",
      "Palm sugar",
      "Fish sauce",
      "Thai basil",
    ],
    allergens: ["Fish", "Tree Nuts"],
    preparationMethod:
      "Curry paste is made from scratch by pounding fresh herbs and spices, then simmered with coconut milk and protein of choice until flavors meld perfectly.",
    prices: {
      30: 749.99,
      50: 1199.99,
      100: 2299.99,
    },
    regularPricePerPax: 32.99,
    imageUrl:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    rating: 4.7,
    ratingCount: 108,
    spicy: true,
    nutritionalInfo: {
      Calories: "380 kcal",
      Protein: "18g",
      Fat: "26g",
      Carbs: "24g",
      Sodium: "620mg",
      Fiber: "3g",
      Sugar: "6g",
      Cholesterol: "45mg",
    },
  },
];

export const menuTypes = [
  { value: "all", title: "All Menu Types" },
  { value: "soup", title: "Soup" },
  { value: "salad", title: "Salad" },
  { value: "beef", title: "Beef" },
  { value: "pork", title: "Pork" },
  { value: "noodle", title: "Noodle" },
  { value: "chicken", title: "Chicken" },
  { value: "seafood", title: "Seafood" },
  { value: "vegetable", title: "Vegetable" },
  { value: "dessert", title: "Dessert" },
  { value: "beverage", title: "Beverage" },
];

export const dietaryOptions = [
  { value: "all", title: "All Dietary Options" },
  { value: "vegetarian", title: "Vegetarian" },
  { value: "vegan", title: "Vegan" },
  { value: "gluten-free", title: "Gluten-Free" },
  { value: "dairy-free", title: "Dairy-Free" },
  { value: "nut-free", title: "Nut-Free" },
];

export const priceOptions = [
  { value: "all", title: "All Price Options" },
  { value: "budget", title: "Budget ($15-25/person)" },
  { value: "standard", title: "Standard ($25-40/person)" },
  { value: "premium", title: "Premium ($40-60/person)" },
  { value: "luxury", title: "Luxury ($60+/person)" },
];
