export const data = {
  name: "awadasdas",
  description: "dasdasdsadsadsfsdfdssfsdfds",
  available: true,
  pricePerPax: 120,
  pricePerPaxWithServiceCharge: 220,
  minimumPax: 10,
  recommendedPax: 30,
  maximumPax: 50,
  options: [
    { category: "Soup", count: 1 },
    { category: "Salad", count: 1 },
    { category: "Beef", count: 1 },
  ],
  inclusions: [
    { typeOfCustomer: "Both", includes: "ssadsada" },
    { typeOfCustomer: "Buffet", includes: "asdasdasd" },
    { typeOfCustomer: "Plated", includes: "asdasdasd" },
  ],
  serviceHours: 10,
  serviceChargePerHour: 100,
  eventType: "Corporate",
  packageType: "Event",
  imageUrl: "",
  totalServiceFee: 1000,
  imageUploadType: "url",
};
